version: '3.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:8080
    networks:
      - default
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/nginx.conf

  scheduler-service:
    build:
      context: .
      dockerfile: scheduler-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=scheduler-service
      - SERVER_PORT=8081
      - JAVA_TOOL_OPTIONS=-Xmx512m
    depends_on:
      - kafka

#    environment:
#      - JAVA_TOOL_OPTIONS="-Xmx512m"
    networks:
      - default

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      - kafka
      - mailhog
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SERVER_PORT=8082
      - JAVA_TOOL_OPTIONS=-Xmx512m
#    environment:
#      - JAVA_TOOL_OPTIONS="-Xmx512m"
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.100.0/24
